### ISSUE TITLE
注册不了，接口显示403

### ISSUE THREAD

**Issue by zifeimo** [easemob/webim-vue-demo#123]
duration: 0
error: "forbidden_service_operation"
error_description: "Service operation not allowed"
exception: "com.easemob.im.exceptions.ForbiddenServiceOperationException"
timestamp: 1680849621351

**Comment by Wster11** [comment]
demo已更改为使用手机号验证码登录, 您说的注册是自己调用接口吗？

**Comment by zifeimo** [comment]
是我的使用问题，多谢回复
