### ISSUE TITLE
VUE3 demo 添加好友出现WebIM.conn.subscribe is not a function

### ISSUE THREAD

**Issue by cvpv** [easemob/webim-vue-demo#124]
vue.esm.js:628 [Vue warn]: Error in v-on handler: "TypeError: WebIM.conn.subscribe is not a function"

**Comment by cvpv** [comment]
看来是我拉取了master分支引起的

**Comment by HuangFeiPeng** [comment]
> 看来是我拉取了master分支引起的

目前vue3-demo还没合并到master分支，如果使用请参考vue3分之的代码。
