### ISSUE TITLE
SDK 版本 4.1.7 ，getServerConversations 方法中 返回 lastMessage 中 time 字段 有误

### ISSUE THREAD

**Issue by devilbao** [easemob/webim-vue-demo#128]
getServerConversations 方法中 返回 lastMessage 中 time 字段 目前结果是返回的是服务器的最新时间，而不是最新一条消息 上传到服务器的时间

**Comment by myZhangDong** [comment]
这是一个已知问题，会尽快修复

**Comment by HuangFeiPeng** [comment]
> getServerConversations 方法中 返回 lastMessage 中 time 字段 目前结果是返回的是服务器的最新时间，而不是最新一条消息 上传到服务器的时间

已修复可以再试下。
