### ISSUE TITLE
中立消息刷新后就变成空白了

### ISSUE THREAD

**Issue by LiuYimin** [easemob/webim-vue-demo#130]
<img width="292" alt="截屏2023-07-05 16 52 11" src="https://github.com/easemob/webim-vue-demo/assets/11698318/95a36a9a-6f9f-4d45-87d8-de8466c5584f">
类似这种消息,刷新后或者换个浏览器登录后,显示的就是异常的空白消息,有头像,没有消息

**Comment by HuangFeiPeng** [comment]
“中立消息”不做存储，本质为本地插入了一条非真实发送的消息，只存在缓存里面，所以刷新之后就不存在了。
2.显示空白消息有头像没有消息，是因为刷新之后从漫游中获取了命令消息，没有针对命令消息做处理所以导致的，这个我们后续处理一下。
