### ISSUE TITLE
发送URL图片消息 图片地址被替换

### ISSUE THREAD

**Issue by JinLuhuan** [easemob/webim-vue-demo#15]
在 WebIMConfig.js中 设置 useOwnUploadFun: true

`sendImage(url, toUserId) {`
`      const id = WebIM.conn.getUniqueId() `
`      const msg = new WebIM.message('img', id)`
`      msg.set({`
`        body: {`
`          type: 'file',`
`          url, // 图片地址来自我的oss服务器`
`        },`
`        to: toUserId, // 接收消息对象（用户id）`
`      })`
`      WebIM.conn.send(msg.body)`
`    },`

发送的图片url为:
http://zsts-supply.oss-cn-shanghai.aliyuncs.com/[_path].png
消息接受方收到的消息content为
http://a1.easemob.com/[_path].png

问题：图片url的hostname被替换

**Comment by QWK-001** [comment]
这个问题应该是修复过了

**Comment by JinLuhuan** [comment]
> 这个问题应该是修复过了

有一段时间没出现了，但就在刚才 9/22 17:05  同样的问题又出现了😓

**Comment by QWK-001** [comment]
具体说一下复现流程

**Comment by JinLuhuan** [comment]
> 具体说一下复现流程

没有特殊流程
两个本地项目  登录两个环信测试账号 A、B
A使用 useOwnUploadFun: true 的方式向B发送图片
B接收到一张被替换了hostname的图片地址

A发送代码如题干
B接收代码
`onPictureMessage:  function (message) {
console.log('接收到图片消息')
    const { from, to, type } = message
    const data = {
      fromHxId: from,
      toHxId: to,
      content: message.url,
      sendTime: message.time,
    }`

**Comment by JinLuhuan** [comment]
收到的地址有一个重定向参数：
http://a1.easemob.com/2020-09-22/n0/1600766100971.png?em-redirect=true

**Comment by QWK-001** [comment]
最新版本sdk暂未复现

**Comment by JinLuhuan** [comment]
> 最新版本sdk暂未复现

easemob-websdk 已更新至3.3.0
应该是我问题描述错误  sdk没问题
是收到的环信图片资源
http://a1.easemob.com/2020-09-22/n0/1600766100971.png?em-redirect=true
404

**Comment by JinLuhuan** [comment]
自己发现了问题
useOwnUploadFun: true 需要设置在接收方
