### ISSUE TITLE
打包后服务器运行报错

### ISSUE THREAD

**Issue by chinahufei** [easemob/webim-vue-demo#2]
EMedia_sdk-dev.js:8525 Uncaught TypeError: Cannot read property 'getSupportedConstraints' of undefined

**Comment by myZhangDong** [comment]
提供一下浏览器版本，是否使用的https，目前音视频在一些不支持的环境会报错

**Comment by SnowBeatRain** [comment]
打包放在本地服务器没有问题，但是放在服务器上就报了上面这个错。没有使用https，并且浏览器使用的是谷歌浏览器，mac和windows都是出现的一样的问题。
