### ISSUE TITLE
2020年4月19日编译后运行浏览器一片空白，报错

### ISSUE THREAD

**Issue by Start1221** [easemob/webim-vue-demo#8]
npm start 运行没问题
使用谷歌浏览器80.0.3987.163版本打开http://127.0.0.1:8080/

console报错
ERROR webrtc-adapter repeated load, safari may dont work

EMedia_x1v1.js?a74b:454 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (EMedia_x1v1.js?a74b:454)
    at Object.parcelRequire.ES8k../Manager (EMedia_x1v1.js?a74b:454)
    at f (EMedia_x1v1.js?a74b:1)
    at p (EMedia_x1v1.js?a74b:1)
    at Object.parcelRequire.ZO4J../components/Util (EMedia_x1v1.js?a74b:474)
    at f (EMedia_x1v1.js?a74b:1)
    at p (EMedia_x1v1.js?a74b:1)
    at Object.parcelRequire.yUjP.../../emedia/webrtc/src/entry (EMedia_x1v1.js?a74b:476)
    at f (EMedia_x1v1.js?a74b:1)
    at p (EMedia_x1v1.js?a74b:1)

**Comment by JCqiu** [comment]
我也是这样
![image](https://user-images.githubusercontent.com/16211027/79719813-e94c5d00-8311-11ea-9ffb-b29df21bfd0b.png)

**Comment by QWK-001** [comment]
请尝试使用， $ HTTPS = true npm run start 启动项目

**Comment by cx1995** [comment]
解决了吗，按照Demo，一步步走，启动白屏

**Comment by wananzys** [comment]
一样的错误

**Comment by QWK-001** [comment]
最新版本谷歌浏览器，仅支持https，demo默认启动是http

**Comment by QWK-001** [comment]
如果启动为白屏：$ HTTPS = true npm run start 启动项目

**Comment by ShawnKuan** [comment]
你好， @QWK-001, 我在VUE-CLI3生成的项目下嵌入web IM，也报这个错误，HTTPS也设置成TRUE 了，
regeneratorRuntime is not defined 的错误我在网上搜了一下，说是要加babel transform runtime 解析。我加上以后还是报错。请问是哪里配置漏掉了吗

![{3D3464AB-D907-4825-9876-4F44AA007D11}_20200508152200](https://user-images.githubusercontent.com/4545007/81382087-6106ee00-9140-11ea-9e48-8e00d346eb94.jpg)
![BDCC8E7A-94AE-4feb-B078-F7A5FB74737B](https://user-images.githubusercontent.com/4545007/81382094-66643880-9140-11ea-9cc3-48550f1456e1.png)

**Comment by QWK-001** [comment]
![B7019FB6F4001D496F68575BC4606AFC](https://user-images.githubusercontent.com/39039355/81382870-aa0b7200-9141-11ea-8ee5-7b4103547654.jpg)
用这个babel试一下

**Comment by QWK-001** [comment]
@ShawnKuan  同时在babel文件里面注入 ```
"plugins": [
    "transform-runtime"
  ]
```

**Comment by ShawnKuan** [comment]
@QWK-001 你好，我花了一下午，对比了一下我自己嵌入的webIM和官方vue-demo的不同，
如果我import 3.0.6 版本(官方版本)的 easemob-webrtc 就不会报runtime的错误，
但是我这边自己用npm 装的easemob-webrtc 是 @3.1.0 ，即使我加了babel的runtime转换还是会报错

**Comment by QWK-001** [comment]
@ShawnKuan 感谢你的反馈，稍后我们会审查一下这个版本

**Comment by n98745** [comment]
我也一直以为是我babel转换配置的问题。万万没想到 = =。写死到"easemob-webrtc": "3.0.8"就好了。

**Comment by QWK-001** [comment]
@n98745  emmmmm~~ 是的，3.1.0的版本目前还在测试中，后续会更新一版

**Comment by QWK-001** [comment]
easemob-webrtc 新版本已经发布，安装最新版本即可
